
# Set the base image to Ubuntu
FROM ubuntu:18.04

# File Author / Maintainer
MAINTAINER abdullah

USER root

#Install Nginx
# Update the repository
RUN apt-get update

# Install necessary tools
RUN apt-get install -y nano wget dialog net-tools

# Download and Install Nginx
RUN apt-get install -y nginx  

# Remove the default Nginx configuration file
RUN rm -v /etc/nginx/nginx.conf
# RUN rm -v /etc/nginx/conf.d/default.conf
# Copy a configuration file from the current directory
ADD nginx.conf /etc/nginx/

# ADD default.conf /etc/nginx/conf.d

# Append "daemon off;" to the beginning of the configuration
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# Expose ports
EXPOSE 6000
# EXPOSE 8080

# Set the default command to execute
# when creating a new container
CMD service nginx start
